<?php
namespace app\jdroom\controller;

use think\Config;
use think\Controller;
use think\Db;
use think\Request;
use think\Session;
use think\Validate;

/**
 * 后台登录
 * Class Login
 * @package app\admin\controller
 */
class Login extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 后台登录
     * @return mixed
     */
    public function index()
    {
//        phpinfo();exit;
        return $this->fetch();
    }

    /**
     * 登录验证
     * @return string
     */
    public function login()
    {
        if ($this->request->isPost()) {
            $data            = $this->request->only(['username', 'password', 'verify']);
            $validate_result = $this->validate($data, 'Login');

            if ($validate_result !== true) {
                $this->error($validate_result);
            } else {
                $where['username'] = $data['username'];
                $where['password'] = md5($data['password'] . Config::get('salt'));
                $admin_user = Db::name('admin_user')->field('id,username,status,times')->where($where)->find();
                if (!empty($admin_user)) {
                    if ($admin_user['status'] != 1) {
                        $this->error('当前用户已禁用');
                    } else {
                        Session::set('admin_id', $admin_user['id']);
                        Session::set('admin_name', $admin_user['username']);
                       $title_name =  Db::name('auth_group_access aga')
                            ->join('os_auth_group ag','aga.group_id=ag.id')
                            ->where('aga.uid',$admin_user['id'])
                            ->field('ag.title')->find();
                        Session::set('group_name', $title_name['title']);
                        Db::name('admin_user')->update(
                            [
                                'last_login_time' => date('Y-m-d H:i:s', time()),
                                'last_login_ip'   => $this->request->ip(),
                                'id'              => $admin_user['id'],
                                'times'              => intval($admin_user['times'])+1
                            ]
                        );
                        createLog('成功登陆后台，登录时间：'.getFormatTime());
                        $this->success('登录成功', 'jdroom/index/index');
//                        jsonSend(1,'jdroom/index/index')
                    }
                } else {
                    $this->error('用户名或密码错误');
                }
            }
        }
    }

    /**
     * 退出登录
     */
    public function logout()
    {
        createLog('成功退出后台，退出时间：'.getFormatTime());
        Session::delete('admin_id');
        Session::delete('admin_name');
        $this->success('退出成功', 'jdroom/login/index',1);
    }
    /**
     * 获取密码
     */
    public function getLightPassword(){
        $mpassword = Request::instance()->param('pass');
        $password =Db::table('os_admin_user')->where(['id'=>Session::get('admin_id')])->value('password');
       $ol= md5($mpassword . Config::get('salt'));
        if($ol == $password)
            $this->success('成功');
        else
            $this->error('失败');
    }
}
